(el-get-bundle elpa:bind-key)
(el-get-bundle elpa:expand-region)
(el-get-bundle elpa:f)
(el-get-bundle elpa:fuzzy)
(el-get-bundle defunkt/gist)
(el-get-bundle elpa:gitignore-mode)
(el-get-bundle elpa:helm-ls-git)
(el-get-bundle elpa:highlight-symbol)
(el-get-bundle elpa:multiple-cursors)
(el-get-bundle elpa:prodigy)
(el-get-bundle elpa:projectile)
(el-get-bundle elpa:smartrep)
(el-get-bundle elpa:smooth-scroll)
(el-get-bundle sigma/tabulated-list)
(el-get-bundle elpa:typescript-mode)
(el-get-bundle tide)
(el-get-bundle elpa:undo-tree)

